[versions]
agp = "8.7.2"
kotlin = "2.0.21"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
