[versions]
agp = "8.7.2"
compileSdk = "36"
kotlin = "2.0.21"
maven-central-publish = "1.3.0"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
maven-central-publish = { id = "tech.yanand.maven-central-publish", version.ref = "maven-central-publish" }
